### ISSUE TITLE
legalPsych calibration curve modifications

### ISSUE THREAD

**Issue by RoyGroncki** [IngerMathilde/legalPsych#2]
Hi @All,
Thank you for this great package. However, is there any way to modify the calibration curves beyond the few arguments outlined here (https://rdrr.io/github/IngerMathilde/legalPsych/man/CA.curves.html)? Specifically, I am trying to change the colour of individual curves to better distinguish them (especially when the curves are very similar making it hard to seperate based solely on the dashes and shapes). Additionally, is there a way to manipulate the text on the axes in a manner similar to the legend text? 

Best regards,
Roy

**Comment by renanbsaraiva** [comment]
Hi Roy,

Many thanks for your interest in the package. 

I have updated the package so that it now produces coloured graphs by default. For editing the graphs, I would suggest storing the calibration curves in a new object and make edits using the ggplot2 documentation.

Here's some example code:
```
CA.rel.object <- CA.rel(data = data, confidence = "LineupConfidence", correct = "LineupAccuracy.Numeric",
                  test = "CAL", var = "LineupChoice", 
                  confidenceLevels = list(c(0,20),c(30,40), c(50,60), c(70,80), c(90,100)), jack = T)

cal.curve <- CA.curves(CA.rel.object)

cal.curve[[1]] +  
  theme(text = element_text(size=20))
```

The same process may be used to change the graphs back to black and white:

```
cal.curve[[1]] +  
  theme(text = element_text(size=20)) +
  scale_color_grey()
```

Kind regards,
Renan

**Comment by RoyGroncki** [comment]
Hi Renan,

Thank you for the prompt assistance. Works like a charm now and the curves are looking stellar. 

Have a great weekend.

Best regards,
Roy
